package hellfrog.common.worldometers;

import java.util.*;

public class TwoLettersCountries {

    public static final Map<String, String> COUNTRIES_MAP_DIRECT;
    public static final Map<String, String> COUNTRIES_MAP_REVERSE;
    public static final List<String> IGNORE_CODES;

    static {
        HashMap<String, String> directMap = new HashMap<>();
        HashMap<String, String> reverseMap = new HashMap<>();
        List<String> ignoreCodes = new ArrayList<>();

        directMap.put("AD","Andorra");
        directMap.put("AE","UAE");
        directMap.put("AF","Afghanistan");
        directMap.put("AG","Antigua and Barbuda");
        directMap.put("AI","Anguilla");
        directMap.put("AL","Albania");
        directMap.put("AM","Armenia");
        directMap.put("AO","Angola");
        directMap.put("AQ","Antarctica");
        directMap.put("AR","Argentina");
        directMap.put("AS","American Samoa");
        directMap.put("AT","Austria");
        directMap.put("AU","Australia");
        directMap.put("AW","Aruba");
        directMap.put("AX","Åland Islands");
        directMap.put("AZ","Azerbaijan");
        directMap.put("BA","Bosnia and Herzegovina");
        directMap.put("BB","Barbados");
        directMap.put("BD","Bangladesh");
        directMap.put("BE","Belgium");
        directMap.put("BF","Burkina Faso");
        directMap.put("BG","Bulgaria");
        directMap.put("BH","Bahrain");
        directMap.put("BI","Burundi");
        directMap.put("BJ","Benin");
        directMap.put("BL","Saint Barthélemy");
        directMap.put("BM","Bermuda");
        directMap.put("BN","Brunei Darussalam");
        directMap.put("BO","Bolivia");
        directMap.put("BQ","Bonaire");
        directMap.put("BR","Brazil");
        directMap.put("BS","Bahamas");
        directMap.put("BT","Bhutan");
        directMap.put("BV","Bouvet Island");
        directMap.put("BW","Botswana");
        directMap.put("BY","Belarus");
        directMap.put("BZ","Belize");
        directMap.put("CA","Canada");
        directMap.put("CC","Cocos (Keeling) Islands");
        directMap.put("CD","Congo, Democratic Republic of the");
        directMap.put("CF","Central African Republic");
        directMap.put("CG","Congo");
        directMap.put("CH","Switzerland");
        directMap.put("CI","Côte d'Ivoire");
        directMap.put("CK","Cook Islands");
        directMap.put("CL","Chile");
        directMap.put("CM","Cameroon");
        directMap.put("CN","China");
        directMap.put("CO","Colombia");
        directMap.put("CR","Costa Rica");
        directMap.put("CU","Cuba");
        directMap.put("CV","Cabo Verde");
        directMap.put("CW","Curaçao");
        directMap.put("CX","Christmas Island");
        directMap.put("CY","Cyprus");
        directMap.put("CZ","Czechia");
        directMap.put("DE","Germany");
        directMap.put("DJ","Djibouti");
        directMap.put("DK","Denmark");
        directMap.put("DM","Dominica");
        directMap.put("DO","Dominican Republic");
        directMap.put("DZ","Algeria");
        directMap.put("EC","Ecuador");
        directMap.put("EE","Estonia");
        directMap.put("EG","Egypt");
        directMap.put("EH","Western Sahara");
        directMap.put("ER","Eritrea");
        directMap.put("ES","Spain");
        directMap.put("ET","Ethiopia");
        directMap.put("FI","Finland");
        directMap.put("FJ","Fiji");
        directMap.put("FK","Falkland Islands (Malvinas)");
        directMap.put("FM","Micronesia (Federated States of)");
        directMap.put("FO","Faroe Islands");
        directMap.put("FR","France");
        directMap.put("GA","Gabon");
        directMap.put("GB","United Kingdom of Great Britain and Northern Ireland");
        directMap.put("GD","Grenada");
        directMap.put("GE","Georgia");
        directMap.put("GF","French Guiana");
        directMap.put("GG","Guernsey");
        directMap.put("GH","Ghana");
        directMap.put("GI","Gibraltar");
        directMap.put("GL","Greenland");
        directMap.put("GM","Gambia");
        directMap.put("GN","Guinea");
        directMap.put("GP","Guadeloupe");
        directMap.put("GQ","Equatorial Guinea");
        directMap.put("GR","Greece");
        directMap.put("GS","South Georgia and the South Sandwich Islands");
        directMap.put("GT","Guatemala");
        directMap.put("GU","Guam");
        directMap.put("GW","Guinea-Bissau");
        directMap.put("GY","Guyana");
        directMap.put("HK","Hong Kong");
        directMap.put("HM","Heard Island and McDonald Islands");
        directMap.put("HN","Honduras");
        directMap.put("HR","Croatia");
        directMap.put("HT","Haiti");
        directMap.put("HU","Hungary");
        directMap.put("ID","Indonesia");
        directMap.put("IE","Ireland");
        directMap.put("IL","Israel");
        directMap.put("IM","Isle of Man");
        directMap.put("IN","India");
        directMap.put("IO","British Indian Ocean Territory");
        directMap.put("IQ","Iraq");
        directMap.put("IR","Iran");
        directMap.put("IS","Iceland");
        directMap.put("IT","Italy");
        directMap.put("JE","Jersey");
        directMap.put("JM","Jamaica");
        directMap.put("JO","Jordan");
        directMap.put("JP","Japan");
        directMap.put("KE","Kenya");
        directMap.put("KG","Kyrgyzstan");
        directMap.put("KH","Cambodia");
        directMap.put("KI","Kiribati");
        directMap.put("KM","Comoros");
        directMap.put("KN","Saint Kitts and Nevis");
        directMap.put("KP","Korea (Democratic People's Republic of)");
        directMap.put("KR","Korea, Republic of");
        directMap.put("KW","Kuwait");
        directMap.put("KY","Cayman Islands");
        directMap.put("KZ","Kazakhstan");
        directMap.put("LA","Lao People's Democratic Republic");
        directMap.put("LB","Lebanon");
        directMap.put("LC","Saint Lucia");
        directMap.put("LI","Liechtenstein");
        directMap.put("LK","Sri Lanka");
        directMap.put("LR","Liberia");
        directMap.put("LS","Lesotho");
        directMap.put("LT","Lithuania");
        directMap.put("LU","Luxembourg");
        directMap.put("LV","Latvia");
        directMap.put("LY","Libya");
        directMap.put("MA","Morocco");
        directMap.put("MC","Monaco");
        directMap.put("MD","Moldova, Republic of");
        directMap.put("ME","Montenegro");
        directMap.put("MF","Saint Martin (French part)");
        directMap.put("MG","Madagascar");
        directMap.put("MH","Marshall Islands");
        directMap.put("MK","North Macedonia");
        directMap.put("ML","Mali");
        directMap.put("MM","Myanmar");
        directMap.put("MN","Mongolia");
        directMap.put("MO","Macao");
        directMap.put("MP","Northern Mariana Islands");
        directMap.put("MQ","Martinique");
        directMap.put("MR","Mauritania");
        directMap.put("MS","Montserrat");
        directMap.put("MT","Malta");
        directMap.put("MU","Mauritius");
        directMap.put("MV","Maldives");
        directMap.put("MW","Malawi");
        directMap.put("MX","Mexico");
        directMap.put("MY","Malaysia");
        directMap.put("MZ","Mozambique");
        directMap.put("NA","Namibia");
        directMap.put("NC","New Caledonia");
        directMap.put("NE","Niger");
        directMap.put("NF","Norfolk Island");
        directMap.put("NG","Nigeria");
        directMap.put("NI","Nicaragua");
        directMap.put("NL","Netherlands");
        directMap.put("NO","Norway");
        directMap.put("NP","Nepal");
        directMap.put("NR","Nauru");
        directMap.put("NU","Niue");
        directMap.put("NZ","New Zealand");
        directMap.put("OM","Oman");
        directMap.put("PA","Panama");
        directMap.put("PE","Peru");
        directMap.put("PF","French Polynesia");
        directMap.put("PG","Papua New Guinea");
        directMap.put("PH","Philippines");
        directMap.put("PK","Pakistan");
        directMap.put("PL","Poland");
        directMap.put("PM","Saint Pierre and Miquelon");
        directMap.put("PN","Pitcairn");
        directMap.put("PR","Puerto Rico");
        directMap.put("PS","Palestine, State of");
        directMap.put("PT","Portugal");
        directMap.put("PW","Palau");
        directMap.put("PY","Paraguay");
        directMap.put("QA","Qatar");
        directMap.put("RE","Réunion");
        directMap.put("RO","Romania");
        directMap.put("RS","Serbia");
        directMap.put("RU","Russia");
        directMap.put("RW","Rwanda");
        directMap.put("SA","Saudi Arabia");
        directMap.put("SB","Solomon Islands");
        directMap.put("SC","Seychelles");
        directMap.put("SD","Sudan");
        directMap.put("SE","Sweden");
        directMap.put("SG","Singapore");
        directMap.put("SH","Saint Helena, Ascension and Tristan da Cunha");
        directMap.put("SI","Slovenia");
        directMap.put("SJ","Svalbard and Jan Mayen");
        directMap.put("SK","Slovakia");
        directMap.put("SL","Sierra Leone");
        directMap.put("SM","San Marino");
        directMap.put("SN","Senegal");
        directMap.put("SO","Somalia");
        directMap.put("SR","Suriname");
        directMap.put("SS","South Sudan");
        directMap.put("ST","Sao Tome and Principe");
        directMap.put("SV","El Salvador");
        directMap.put("SX","Sint Maarten (Dutch part)");
        directMap.put("SY","Syrian Arab Republic");
        directMap.put("SZ","Eswatini");
        directMap.put("TC","Turks and Caicos Islands");
        directMap.put("TD","Chad");
        directMap.put("TF","French Southern Territories");
        directMap.put("TG","Togo");
        directMap.put("TH","Thailand");
        directMap.put("TJ","Tajikistan");
        directMap.put("TK","Tokelau");
        directMap.put("TL","Timor-Leste");
        directMap.put("TM","Turkmenistan");
        directMap.put("TN","Tunisia");
        directMap.put("TO","Tonga");
        directMap.put("TR","Turkey");
        directMap.put("TT","Trinidad and Tobago");
        directMap.put("TV","Tuvalu");
        directMap.put("TW","Taiwan");
        directMap.put("TZ","Tanzania");
        directMap.put("UA","Ukraine");
        directMap.put("UG","Uganda");
        directMap.put("UK", "UK");
        directMap.put("UM","United States Minor Outlying Islands");
        directMap.put("US","USA");
        directMap.put("UY","Uruguay");
        directMap.put("UZ","Uzbekistan");
        directMap.put("VA","Holy See");
        directMap.put("VC","Saint Vincent and the Grenadines");
        directMap.put("VE","Venezuela (Bolivarian Republic of)");
        directMap.put("VG","Virgin Islands (British)");
        directMap.put("VI","Virgin Islands (U.S.)");
        directMap.put("VN","Viet Nam");
        directMap.put("VU","Vanuatu");
        directMap.put("WF","Wallis and Futuna");
        directMap.put("WS","Samoa");
        directMap.put("YE","Yemen");
        directMap.put("YT","Mayotte");
        directMap.put("ZA","South Africa");
        directMap.put("ZM","Zambia");
        directMap.put("ZW","Zimbabwe");

        directMap.forEach((k,v) -> reverseMap.put(v, k));

        ignoreCodes.add("North America");
        ignoreCodes.add("Asia");
        ignoreCodes.add("South America");
        ignoreCodes.add("Europe");
        ignoreCodes.add("Africa");
        ignoreCodes.add("Oceania");
        ignoreCodes.add("World");
        ignoreCodes.add("Total:");

        Collections.sort(ignoreCodes);

        COUNTRIES_MAP_DIRECT = Collections.unmodifiableMap(directMap);
        COUNTRIES_MAP_REVERSE = Collections.unmodifiableMap(reverseMap);
        IGNORE_CODES = Collections.unmodifiableList(ignoreCodes);
    }
}
